### ISSUE TITLE
Makefile.in disagrees with DESCRIPTION SystemRequirements

### ISSUE THREAD

**Issue by mtmorgan** [RGLab/CytoML#118]
The SystemRequirements indicated that CXX11 is required. This is consistent with the Windows Makefile.win https://github.com/RGLab/CytoML/blob/70484acf03c75717ff3329570799ffbc7881ca85/src/Makevars.win#L2, but not with Makefile.in https://github.com/RGLab/CytoML/blob/70484acf03c75717ff3329570799ffbc7881ca85/src/Makevars.in#L9.

It seems like only CXX11 is required; can Makefile.in be updated to reflect the actual system requirements?

@lsmatott

**Comment by mikejiang** [comment]
@mtmorgan ,
Here is a little background info:
Months ago we were trying to switch to filesystem library built in c++ standard(requires c++17) so that we don't need to bundle the copy of boost fs lib (which occasionally conflicts with `BH` headers everytime when it upgrades its boost).
But it turned out c++17 support was not available in compilers of some of bioc servers (mac or win). Then we ended up reverted back to boost fs lib.

But yeah, you are right, CXX17 is not needed. I've pushed changes. thanks for pointing it out!
