### ISSUE TITLE
GatingSet2FlowJo

### ISSUE THREAD

**Issue by mikejiang** [RGLab/CytoML#2]
We may consider exporting `flowJo` workspace instead of standard `gatingML` files due to the lack of support of the latter from `flowJo`.
We've been down that path before, @gfinak , do you recall why it was halted?
@jspidlen, since you've implemented `workflow2FlowJo` in `flowUtils`, I'd like have your input on this as well.

**Comment by raphg** [comment]
I think that it's a reasonable idea. I am not sure proper GatingML will ever be supported.

**Comment by jspidlen** [comment]
Hi Mike,

We've been down that path before, @gfinak , do you recall why it was halted?


Two main issues from what I recall,

(i) it was hard to match FlowJo's data transformations due to the lack of
documentation of those, plus the transformations used to be implemented
slightly differently on Mac vs Windows, and the actual transformation were
dependent on certain keyword values from the related FCS files. I think the
Mac-specific version is pretty much gone by now, and you guys may have
figured out the transformation details by now, so possibly this isn't an
issue any more.

(ii) The workspace wasn't really documented all that well, and FlowJo had
too many versions of the workspace format. This I think is still the case...

@jspidlen, since you've implemented workflow2FlowJo in flowUtils, I'd like
> have your input on this as well.


No, I haven't. Code in that file has been written by Florian Hahne in 2009,
and there has been a minor addition to it by Nishant Gopalakrishnan in
2010, but I believe it's never been finished, neither documented. Also,
code in that file was referencing some non-existing functions, and there
have always been some warnings about it during the R CMD check. It's been 6
years, nobody's using it and I don't even know what it's supposed to do, so
actually just yesterday, I commented out everything in that file.

Josef

**Comment by mikejiang** [comment]
@jspidlen , thanks for the input. `Transformation` may not be an issue since `logicle` is pretty comparable to `flowJo biexp`. At least we did not see the issue during the conversion from `logicle` to `cytobank`'s `arcsinh`. I think it definitely worth a try.

**Comment by mikejiang** [comment]
So far 5 different `Gatingsets` (3 manual + 2 auto) has been successfully exported to  `flowJo`.  
`biexp`,  `fasinh` and `calibration table` are currently supported.
