### ISSUE TITLE
"Failed to import the GatingML file xxxxx" 

### ISSUE THREAD

**Issue by tjburns08** [RGLab/CytoML#27]
Mike, 

I have done some further investigation with respect to the notorious "failed to import" message in Cytobank, that we have been getting more recently when trying to import the GatingML from flow data into Cytobank. To refresh, when I make gates in FJ for flow cytometry files, use CytoML to make a GatingML file, and pass said GatingML file into Cytobank, I get the notorious message we have discussed on other threads:  

<img width="578" alt="screen shot 2017-11-04 at 2 49 57 pm" src="https://user-images.githubusercontent.com/21996870/32406053-3bf70ed4-c171-11e7-8ea8-23c7184bfbcd.png">

I have found two things that may be related. 

The first is that this "failed to import" message only occurs with markers that are not linear by default (eg not scatter). Below is an example from polygon gate.

<img width="627" alt="screen shot 2017-11-04 at 2 40 46 pm" src="https://user-images.githubusercontent.com/21996870/32405879-32da917a-c16e-11e7-86e0-de69b771ed12.png">

The second is that older versions of CytoML produce xml files that still successfully import into Cytobank. In the following example, the older version of CytoML is used on top, and the latest version of CytoML is used on the bottom.

<img width="686" alt="screen shot 2017-11-04 at 2 55 14 pm" src="https://user-images.githubusercontent.com/21996870/32405989-332d1952-c170-11e7-95c7-73d01594b40a.png">

This suggests that a change to CytoML and the related packages could be leading to this problem. There could be a number of reasons for the error, of course (including the older version of R, etc), but a closer look at the xml file reveals that the coordinates within the xml generated by the older version of CytoML has a (logicle?) transformation. 

<img width="597" alt="screen shot 2017-11-04 at 2 56 34 pm" src="https://user-images.githubusercontent.com/21996870/32405995-63c07168-c170-11e7-9534-5f215238fa53.png">

This is interesting, given my previous observation that the non-linear markers are the ones that are affected by this import error. So my question: is it possible that doing this "coordinate transform" for the new xml file could lead to the files being successfully read into Cytobank again? In a separate email, I'll send you the relevant wsp file and xml files. 

Thanks for your help!

**Comment by mikejiang** [comment]
Yes, it has to do with the latest change in #26 .
This is something that has concerned and bothered me from the beginning when I wrote  `GatingSet2cytobank` function.
To ensure the new changes do not introduce new bugs, we need the streamlined test cases to be added to the existing package unit test suite. But without the `cytobank` APIs being exposed to me (since it is only accessible for premium users), it is very hard for me to do so. I hope you can talk to cytobank about this issue so that this kind of error could be captured by the automated test case instead of costing you of quite some efforts to troubleshoot  in future (which you've done impressively well so far).

Anyway, I've pushed the fix and done some limited testing on my end, pull the latest CytoML and let me know if it works for you.

**Comment by tjburns08** [comment]
Mike, this is a good point. I will talk with @katdrake about building an automated test case pipeline, and perhaps getting you access to the APIs. I consider this a high priority issue moving forward, and I will keep you posted. Thanks again for your help. I will close this thread as soon as I have tested your latest changes.
