### ISSUE TITLE
Feature request: Import Cytobank Workspace

### ISSUE THREAD

**Issue by bjreisman** [RGLab/CytoML#48]
It would be very useful to be able to import a cytobank experiment into flowCore, including all of the preprocessing steps which are not included in the cytobankGatingML file. This functionality could be similar to the `openWorkspace()` function in flowWorkspace, but for cytobank instead of flowJo. 

The functions implemented in CytoML and flowWorkspace allow for reproducing gating schemes from cytobank, but do not allow for importing the complete workspace: including scales (for non-gated channels), sample tags, compensations (those not included in compensations), and panels.

Ideally, I would like to be able to build a transformer list which reproduces the scales defined in cytobank, rename markers according to panels, and include pData as defined by sample tags. 

I could imagine two approaches to implementing this which would both be useful:
1. Importing a locally stored experiment which has been exported from cytobank as an ACS file. 
(This data appears to be included in the `cytobank_experiment.yaml` included in the ACS file.)
2. Importing an experiment from cytobank directly using the CytobankAPI package. 
(This data can be accessed from a series of API calls to cytobank, which could be bundled together as a single workspace object). 

I'd be happy to contribute to implementing these features, but wasn't sure if they'd be more appropriate for flowWorkspace, CytoML, or a separate package all together.

**Comment by mikejiang** [comment]
Let's start with the local ACS. and I will try to extend `CytoML::cytobank2GatingSet` so that it will (optionally) parse the entire `ACS` folder. At a brief glance, we just need to parse the yaml file that stores pdata(i.e. sample tags) and renamed markers(i.e. panel info) and apply them to the `GatingSet` that is parsed from cytobankGatingML file. Since parsing yaml should be pretty straight forward, I'll first take a stab myself and let you know if I need more help from you. (you can certainly help with testing)
One quick question:
What's the difference between the compensation stored in gatingML file and the one in yaml?

**Comment by bjreisman** [comment]
Awesome!

I'm not entirely sure that they are different, but one thing that caught me off guard at first is that within cytobank, gates are tied to a specific scale and compensations but the inverse is not true. Since the gatingML file only contains the transforms for the gated channels, I'd be worried that it only contains the compensations relevant to the gated channels as well. I.e. the YAML file may contain compensations that are not included in the gatingML file. I'll double check if that's true.

**Comment by bjreisman** [comment]
I stand corrected, the gatingML file does appear to contain all compensations from the experiment.

**Comment by mikejiang** [comment]
We typically associated only one compensation (that is actually used by the experiment) to the `GatingSet` , which is the final product from the current importing API `cytobank2GatingSet`. It seems to me that we do  need a `cytobankWorkspace` object (similar to `flowJoWorkspace` as you previously suggested) to represent `experiment` concept from `cytobank`, for which we will provide these methods
* getCompensations (include all compensations)
* getTransformations (include all scales for non-gated channels)
* pData( parsed from sample tags)
* parseWorkspace 
  * calling existing `cytobank2GatingSet` to convert gatingML to `GatingSet`
  * attach `pData` 
  * update `markers` based on `panel` info
  * fill the counts based on csv from ACS folder (may not be always possible due to the lacking unqiue gate path from the stats exported from cytobank)

**Comment by bjreisman** [comment]
That sounds exactly like what's needed! I hadn't considered the 'counts' data, but that could be handy as well. One issue I ran into in my attempt to implement this is that the FCS files included in the ACS file were named by their cytobank fcsId, not their original filename. The `fcsFiles` files section in the YAML file has the original file names so that might be something worth parsing as well. 

Along the same lines, would it be possible for different `flowFrames` within the gatingset to have different `markerNames`? The panels section has the channel to marker data for each panel, but the `fcsFiles` section has the information about which panel goes to which fcs file (therefore you may need to update the markers based on both the `panel` info and the `fcsFiles` info). 

Thank you for considering this feature.

**Comment by mikejiang** [comment]
Yeah, `YAML` file can be used to convert id to fcs file name.
`GatingSet` itself does allow different marker names across samples(i.e. `flowFrames`) as long as `channel` names are consistent.

**Comment by mikejiang** [comment]
I implemented `cytobankExperiment` class instead (more aligned with cytobank's terminology) and its accessor APIs. `cytobank2GatingSet` is overloaded and can directly apply to `cytobankExperiment` object (The original `cytobank2GatingSet` still works for `gatingML` file itself)
see example http://rpubs.com/wjiang2/471345
