### ISSUE TITLE
Exported Flowjo Workspace blank 

### ISSUE THREAD

**Issue by john-lee-johnson** [RGLab/CytoML#8]
Hello, very interested in using CytoML to export my GatingSet for others to use FlowJo for their own exploration of the data. However when I export my GatingSet using `GatingSet2flowJo` the resulting wsp file is empty, am I supposed to do something special to the GatingSet before it is ready to be exported? Additionally, do I need to put the fcs files in the same folder as the exported wsp file?

**Comment by mikejiang** [comment]
Was the `GatingSet` generated based on the new workflow (see#5)?
`GatingSet2flowJo` only exports `wsp` file and once `GatingSet` is created it no longer needs `fcs` files thus the location of `fcs` is not relevant.
Could you share one example `GatingSet` for me to look at? (simply do `gs_small <- clone(gs[1])`)

**Comment by john-lee-johnson** [comment]
I believe so, I applied compensation and transformation directly to the GatingSet. Sorry for the ignorance, but how do I share the GatingSet? I cloned it, but not sure the best way to share it with you. Thanks!

**Comment by mikejiang** [comment]
You can either post it here or share it though dropbox and email the link to wjiang2@fhcrc.org

**Comment by mikejiang** [comment]
My export looks fine
```r
tmp <- tempfile(fileext = ".wsp")
GatingSet2flowJo(gs, tmp)
```
![image](https://cloud.githubusercontent.com/assets/1385649/17906180/20cf8504-692b-11e6-9939-154bacf0a211.png)

Except that the `name` attribute under `sampleNode` was screwed up due to the `factor` type of column `name` in `pData` (not sure if this is the reason you said it was `blank`)
```r
> str(pData(gs))
'data.frame':	1 obs. of  2 variables:
 $ name    : Factor w/ 6 levels "30min_37_restain",..: 4
  ..- attr(*, "names")= chr "60min_37_restain"
```
I will push a fix by `coercing` it to `character`.

**Comment by john-lee-johnson** [comment]
What program did you open that in? I tried exporting the same `gs_small` as you have, but mine comes up blank in FlowJo 10. Appreciate the help!

**Comment by mikejiang** [comment]
I fixed the `factor` issue
![image](https://cloud.githubusercontent.com/assets/1385649/17907517/296d742c-6931-11e6-96d8-b8fa0ce66cac.png)
Pull the latest fix and try again. I no longer have access to `flowJo` so simply opened it by an `eclipse plugin` xml editor. 

By the way, I noticed that you sent me the archived `GatingHierarchy` instead of `GatingSet`. It is probably because you subsetted it by `[[` instead of `[`.

**Comment by mikejiang** [comment]
Also, your `name` column is a short name other than the actual `fcs` filename, I wonder if it is the cause for `flowJo` not being able to locate the data.
```r
> pData(gs)
                             name                                  Filename
60min_37_restain 60min_37_restain CXCR5-Biotin_001_60min_37_restain_013.fcs
```
So if it is still not working after you installed the fix, try to modify the `name`, see if it helps
```r
pData(gs)[["name"]] <- pData(gs)[["Filename"]]
```

**Comment by john-lee-johnson** [comment]
I changed the `name` to the actual `fcs` filename and updated to the latest version. The workspace now opens with the gates and it is linked to the file, however when I open the plots in FlowJo no events show up. If I open an unrelated fcs file I can apply the gates to that file and the events show up normally. Any ideas? I updated the Dropbox link I sent you earlier to include the GatingSet object, the wsp, and the fcs file.

Thanks for all the help!

**Comment by mikejiang** [comment]
I found forward slash `/` in the `channel` names of your `data`,
```r
$P7     660/20 Red-A   GP33 262144     -111   262143
$P8     710/50 Red-A   CD44 262144     -111   262143
$P9     780/60 Red-A   ZNIR 262144     -111   262143
$P10   515/20 Blue-A CD45_2 262144     -111   262143
```
 which may contribute to the issue you observed because `flowJo` tends to replace it with `_` when it sees `/` in `data`.
I will have to add the `preprocessing` step to `GatingSet2flowJo` call to take care of this replacement before exporting `xml`.

**Comment by john-lee-johnson** [comment]
Unfortunately that is how the channels are named on our cytometer. I was wondering if it is possible to replace the channel names in the fcs file after reading it in. Thanks again!

**Comment by mikejiang** [comment]
It is not just `flow data` that needs to be modified. `transformation`, `compensation` and `gates` all need to be treated. I will make changes to code.

**Comment by mikejiang** [comment]
@john-lee-johnson , pull the latest fix. Since most of your gates(except `lymph`) are `1D` gate, my `flowJo` won't be able to show these gates in `2D` view unless I choose the `y-axis` as `Histogram`. 
Based on the `flowJo` manual,  there is some place you can change the setting to enable `1d` gate display in `2d` scatter plot , but my trial version somehow doesn't work.

**Comment by john-lee-johnson** [comment]
Yes it works perfectly, thank you!
