### ISSUE TITLE
Temporary memory (on disk) not cleared

### ISSUE THREAD

**Issue by SofieVG** [RGLab/CytoML#84]
I am using the CytoML::open_flowjo_xml and CytoML::flowjo_to_gatingset functions (in the FlowSOM::getFlowJoLabels function for ease of use in the examples in the FlowSOM package). 
In previous versions of flowWorkspace/CytoML, I also had to close the workspace again, but in the latest version this function does not seem available anymore. However, I have the impression that lots of data stays stored in the R tmp folder which is created. Which function do I need to call to clean up these h5 files?

Many thanks in advance, 
Sofie

**Comment by mikejiang** [comment]
You maybe referring to the `closeWorkspace` (or `flowjo_ws_close`) function which is responsible for free the memory (not disk) of `xml` (not `h5`). It is no longer needed since we've ported entire flowJo parsing code into `c++` and the garbage collection is automatically taking place once the object goes out of scope. ( There is a caveat related to this, which is explained in detail in #81 , but I don't think it is relevant to you at this point).

Regarding to the `h5` created for `GatingSet`,  if you are using the latest development branch of bioc (or github). @jacobpwagner has added `gs_cleanup_temp` convenient function to delete the `h5` files. But be aware that once h5 is deleted. your `gs` object is no longer usable. 
Also if you eventually call  `save_gs` setting  `cdf="move"`, then the `h5` from `temp` folder is automatically removed and no need for extra cleanup steps.

**Comment by gfinak** [comment]
Thanks, Mike. That's a great summary.

Greg Finak
